### ISSUE TITLE
Add HONEYCOMB_API_KEY envvar support

### ISSUE THREAD

**Issue by jharley** [honeycombio/terraform-provider-honeycombio#117]
The Honeycomb standard has become `HONEYCOMB_API_KEY` so the provider should support it too in the name of consistency.

This will deprecate but continue to support the current `HONEYCOMBIO_APIKEY` but drop support altogether for the 1.0.0 release.

**Comment by teddylear** [comment]
@jharley I can take a look into this if that's alright.

**Comment by jharley** [comment]
Closed by #187
