### ISSUE TITLE
Create a clean dataset before running acceptance tests to have more deterministic behaviour

### ISSUE THREAD

**Issue by kvrhdn** [honeycombio/terraform-provider-honeycombio#12]
As @fitzoh proposed on the Honeycomb Slack: before running the acceptance tests, we could initialize a fresh dataset with all the expected columns. Contributors would only need to supply an API key to run all the tests.

This would avoid a lot of manual setup work and make the tests more deterministic. Currently, the tests will fail if the dataset is missing certain columns (i.e. `duration_ms`, `app.tenant`).

**Comment by mveitas** [comment]
Link to discussion around creating a dataset before running tests: https://honeycombpollinators.slack.com/archives/C017T9FFT0D/p1596453822070400

**Comment by jharley** [comment]
This has partially been resolved with the addition of [setup-testsuit-dataset](../blob/main/scripts/setup-testsuite-dataset) which runs at the start of the CI process and creates the named dataset and any missing columns defined columns in an idempotent fashion.

It *felt* "good enough" at the time, but I'm open to the idea of adding an option to remove all the columns from the dataset at the start? The Dataset API doesn't currently support `DELETE` in the name of misuse (as pointed out in the linked Pollinators thread above), so it would have to be done at the column level 🤔 

Any thoughts, @fitzoh or @mveitas?

**Comment by jharley** [comment]
I'm going to close this out. Please reopen if you have concerns or suggestions for improvements.
