### ISSUE TITLE
Creating honeycomb board with multiple panels using terraform fails with 500 Internal server error

### ISSUE THREAD

**Issue by kgarigipati** [honeycombio/terraform-provider-honeycombio#147]
**Versions**
![Screen Shot 2022-04-10 at 7 44 08 PM](https://user-images.githubusercontent.com/35507587/162656431-3c453aad-a6a6-4b8c-a662-13e78148c427.png)

**Steps to reproduce**

1. Run `terraform plan` to view the plan to create a board in honeycomb which has 23 panels
2. Run `terraform apply` to finish creating a board with multiple panels(in our case its 23 panels)

Expected Result: It should successfully create the board.
Actual Result: It throws `500 Internal Server Error: Something went wrong!
<img width="856" alt="Screen Shot 2022-04-10 at 7 59 41 PM" src="https://user-images.githubusercontent.com/35507587/162657904-e338dadb-f997-432a-b64f-c3c64dfbbf73.png">

**Additional context**

It seems like a honeycomb API timeout is happening when we try to create a board with multiple panels.

We can work around it by trying to create 3 panels at a time and that seems to work, but it's a pain to create a board that has more than 20 panels.

Would be great if we could increase honeycomb API timeout or if something else needs to be fixed.

**Comment by dstrelau** [comment]
FYI: This is an API bug, not specific to Terraform. We're now tracking this internally, and I'll provide an update here once we believe it to be fixed.

**Comment by jharley** [comment]
I believe this has been resolved "server side". Please let us know if the issue remains.
