### ISSUE TITLE
add support for "send alert every time threshold is met"

### ISSUE THREAD

**Issue by nicolasburtey** [honeycombio/terraform-provider-honeycombio#163]
the ui have an option to trigger an option every time threshold is met

![image](https://user-images.githubusercontent.com/11156370/168343682-ee5dbeb2-a51b-4cac-9e16-d754a0de6ef8.png)

the [terraform provider](https://registry.terraform.io/providers/honeycombio/honeycombio/latest/docs/resources/trigger) doesn't have this option.
this would be very useful as all our triggers are managed by terraform

**Comment by jharley** [comment]
Hi, @nicolasburtey! The API endpoint for this feature is being worked on now and once it is ready the provider will support it.
