### ISSUE TITLE
blocked when moving a recipient from inline to its own resource

### ISSUE THREAD

**Issue by ryanking** [honeycombio/terraform-provider-honeycombio#205]
**Versions**

provider v0.8.0

**Steps to reproduce**

Sorry I don't have some of the original hcl, and also can't share what I have as-is.

1. create a trigger with inline recipient definition

```hcl
resource "honeycombio_trigger" "tasks-trigger" {
 ...
  recipient {
    type   = "slack"
    target = "foo:
  }
}
```

2. refactor to make the recipient a separate resource

```hcl
resource "honeycombio_trigger" "tasks-trigger" {
 ...
  recipient {
    type   = "slack"
    target = honeycomb_slack_recipient.recipient.id
  }
}

resource "honeycombio_slack_recipient" "recipient" {
  channel = "foo"
}
```

3. 

```terraform plan
...
│ Error: invalid value for channel (channel must begin with `#` or `@`)
```

4. 
```hcl
resource "honeycombio_trigger" "tasks-trigger" {
 ...
  recipient {
    type   = "slack"
    target = honeycomb_slack_recipient.recipient.id
  }
}

resource "honeycombio_slack_recipient" "recipient" {
  channel = "#foo"
}
```

5. 

```
terraform plan
...

  # honeycombio_trigger.tasks-trigger will be updated in-place
  ~ resource "honeycombio_trigger" "tasks-trigger" {
        id          = "..."
        name        = "..."
        # (6 unchanged attributes hidden)

      ~ recipient {
          ~ id     = "qzukyAgbiGu" -> (known after apply)
            # (2 unchanged attributes hidden)
        }

        # (1 unchanged block hidden)
    }

  # honeycombio_slack_recipient.recipient will be created
  + resource "honeycombio_slack_recipient" "recipient" {
      + channel = "#foo"
      + id      = (known after apply)
    }

$ terraform import honeycombio_slack_recipient.recipient qzukyAgbiGu
[success]
```
6.

```
terraform apply
...
│ Error: 409 Conflict: Recipient of type "slack" already exists with the details provided.
```

**Comment by jharley** [comment]
@ryanking thanks for taking time to file this!

If you do in fact have a Slack Recipient for the channel `#foo` already (which, it seems you do) then you would need to import the recipient into your state under Terraform's control to avoid the conflict error on creation.

Using your HCL above as an example, something like this should do it:

`terraform import honeycombio_slack_recipient.recipient qzukyAgbiGu`

Alternatively, you could skip the import and use the new datasource to look it up:

```hcl
data "honeycombio_recipient" "slack-foo" {
  type    = "slack"

  filter_detail {
    name  = "channel"
    value = "#foo"
  }
}
```

Does either of these approaches solve your issue?

**Comment by ryanking** [comment]
@jharley yes I did do an import. not sure why I left that out, but it was somewhere around step 3 or 4. I will try again to see if maybe I did it in the wrong order

**Comment by jharley** [comment]
Please let me know! I just did the above: successfully imported the recipient after the refactor and then got a "no changes" plan

**Comment by jharley** [comment]
Hey, @ryanking. Any update on being able to reproduce this?

**Comment by jharley** [comment]
I'm going to close this out as I've not heard back and can't reproduce myself. Please re-open the issue (or a new one) if this is still a problem. :)
