### ISSUE TITLE
Provider treats default operation (COUNT) in query specification as missing config if it's not mentioned explicitly

### ISSUE THREAD

**Issue by kkapoorOS** [honeycombio/terraform-provider-honeycombio#238]
**Versions**
Using terraform Honeycomb provider version 0.11.0

**Steps to reproduce**

1. In terraform, create a HC query with the `COUNT` operation (since `COUNT` is the default `op` you don't need to specify it explicitly) using the query specification (https://docs.honeycomb.io/api/query-specification/#fields-on-a-query-specification)
2. Run a terraform plan and terraform apply - this creates the query.
3. Run terraform plan again, and even though the query is already created, terraform shows a diff as if the configuration has drifted.

**Additional context**
With some tinkering around, I figured out the issue. Since `COUNT` is the default operation, you don't need to specify that in the query specification, however the terraform HC provider isn't able to detect that. When we run a terraform plan (after already running terraform apply), the provider compares the query to the configuration and see the operation `COUNT` stuff in the query in HC, but since this code block isn't explicitly mentioned in the config, it concludes that there's been a drift and decides it must replace the query again.

To resolve this, the HC provider should be able to detect default values, or at the very least, the terraform documentation should mention this behaviour in the examples provided.

**Comment by jharley** [comment]
@kkapoorOS Thanks for reporting this! I believe this should be resolved in version 0.11.2 of the provider (released earlier this week).

Can you confirm?

**Comment by jharley** [comment]
@kkapoorOS I'm going to close this issue as I believe it to be resolved. Please re-open the issue if it has not and we'll investigate.
