### ISSUE TITLE
adding `expand_json_depth` after creation causes drift

### ISSUE THREAD

**Issue by jmhodges-color** [honeycombio/terraform-provider-honeycombio#273]
**Versions**
0.13

**Steps to reproduce**

1. Have a previously created dataset called `foo`.
2. Add a `honeycombio_dataset` for `foo` with the default `expand_json_depth = 0`
3. Have someone update `expand_json_depth` through the Honeycomb API (not through the provider) to 1
4. Update the `honeycombio_dataset` for `foo` to `expand_json_depth = 1`.
5. Run `terraform apply` and see success
6. Run `terraform plan` and see that the `expand_json_depth` in the terraform state is still set to 0

**Additional context**
This went away on a `terraform refresh`

**Comment by jharley** [comment]
My suspicion is that this was a result of version incarnation of caching which has since been rebuild. I can no longer reproduce this so I'm going to close out the issue.
