### ISSUE TITLE
Changing recipient details for Slack type recipient in honeycombio_burn_alert causes 422 failure

### ISSUE THREAD

**Issue by hdenman-stripe** [honeycombio/terraform-provider-honeycombio#322]
**Versions**
0.13.1, 0.15.1

**Steps to reproduce**
This is just the same as https://github.com/honeycombio/terraform-provider-honeycombio/issues/303, except that it pertains to `honeycombio_burn_alert` rather than `honeycombio_trigger`

**Additional context**
I'm sorry I don't have a minimal repro; I use terraform behind a wrapper, rather than directly.

**Comment by jharley** [comment]
Related to #263
