### ISSUE TITLE
Add SLO Data source

### ISSUE THREAD

**Issue by BouchaaraAdil** [honeycombio/terraform-provider-honeycombio#332]
### **Is your feature request related to a problem? Please describe.**

we came to a stage where we needed the SLO id to use it in slo description and other use cases (this may fail when the slo has not yet been created cause of the filter value linked)
### **Describe the solution you'd like**
I would like to have a data source for SLOs that can be filtered by dataset, name ...

**Comment by jharley** [comment]
For being able to filter by name, is `starts_with` sufficient for your use case or would you prefer something like the [honeycombio_recipients datasource](https://registry.terraform.io/providers/honeycombio/honeycombio/latest/docs/data-sources/recipients#get-all-email-recipients-matching-a-specific-domain)'s `detail_filter`?

**Comment by jharley** [comment]
Decided that a `detail_filter` was the most flexible choice in the end.
