### ISSUE TITLE
Expose threshold option to set number of triggers before sending an alert

### ISSUE THREAD

**Issue by emilssolmanis** [honeycombio/terraform-provider-honeycombio#343]
We're using Honeycomb triggers to drive our alerting. We can terraform most things, but we've now hit a use case where we want to only trigger the alert after the threshold is breached X times in a row. In our case this is due to a spiky request pattern, we're addressing this in due time, but would for now like to stop it triggering alerts to avoid fatigue, and still keep _some_ alerting for more persistent request latency problems. This is common functionality available out of the box in, e.g., AWS CloudWatch, so intuitively seems like it should be available.

We can see the option in the UI, but it doesn't seem to be exposed on the TF provider.

We'd like the "Send an alert after the threshold has been met X times" configuration option (see screenshot) exposed via Terraform.
<img width="835" alt="image" src="https://github.com/honeycombio/terraform-provider-honeycombio/assets/663720/578a644c-2588-453a-aedc-a1fb4d2362fd">

We'll delete the Terraformed trigger and create one manually for now, but this is suboptimal because our default is Terraform, and all other dashboards and Honeycomb related setup lives in Terraform. It will cause unnecessary extra effort, and possibly confusion for developers who come across this.

**Comment by jharley** [comment]
@emilssolmanis This is an Early Access (EA) feature still under active development and not yet available to the majority of Honeycomb customers.

Once the feature is ready for General Availability (GA) it is planned to be added to the `honeycombio_trigger` resource.

FWIW, you should be able to configure everything but that setting in Terraform and then go to the UI (or PUT via the API) to change that particular threshold.

**Comment by jharley** [comment]
Hey, @emilssolmanis: support for this just went out with v0.16.0 of the provider

**Comment by emilssolmanis** [comment]
@jharley Thanks for the ping, we shall undo hacks!
