### ISSUE TITLE
Support Graph Settings for queries

### ISSUE THREAD

**Issue by fitzoh** [honeycombio/terraform-provider-honeycombio#37]
These options don't appear to be supported by the API at the moment, but it would be nice to be able to generate graphs using these features (I was trying to terraform a graph that used stacked graphs)
<img width="263" alt="Screen Shot 2020-10-16 at 5 51 32 PM" src="https://user-images.githubusercontent.com/131809/96311801-4cc0fa00-0fd8-11eb-87c3-6c596921c512.png">

**Comment by jharley** [comment]
Support for managing board query graph settings just went to production. Unblocking this to be picked up shortly.
