### ISSUE TITLE
Make `dataset` optional for the honeycomb_query resource

### ISSUE THREAD

**Issue by bmbferreira** [honeycombio/terraform-provider-honeycombio#383]
**Is your feature request related to a problem? Please describe.**

Currently it is always required to provide a dataset for the [honeycomb_query resource](https://registry.terraform.io/providers/kvrhdn/honeycombio/latest/docs/resources/query) however on honeycomb UI I can query all the datasets at once on the same `environment`:
<img width="372" alt="Screenshot 2023-10-26 at 10 42 22" src="https://github.com/honeycombio/terraform-provider-honeycombio/assets/626180/314adcab-5d1e-4dfb-81eb-8a068435b152">

**Describe the solution you'd like**

I would like to have the same behavior that we have on UI and make the `dataset` parameter as optional. This way I could cover multiple datasets in the same query instead of creating multiple queries, one for each dataset.

**Describe alternatives you've considered**
I will have to create multiple queries, one for each dataset.

**Additional context**

**Comment by jharley** [comment]
👋🏻 Hi, @bmbferreira!

The `honeycombio_query` resource mirrors the "All datasets" language in the UI by having you set `dataset = "__all__"` to create an environment wide query.

```hcl
resource "honeycombio_query" "example" {
  dataset    = "__all__"
  query_json = <<-EOH
{
  "calculations": [{"op":"COUNT"}]
}
EOH
}
```

Does that get you the functionality you're looking for?

**Comment by bmbferreira** [comment]
Hi! yes that works! was not aware of the `__all__`. Thanks!

**Comment by jharley** [comment]
No problem!

I also just noticed the doc link you posted is to an old version of the provider (in the namespace of the original author before we adopted it). If you go to the [current documentation for the query resource](https://registry.terraform.io/providers/honeycombio/honeycombio/latest/docs/resources/query#argument-reference) there is a note about using `__all__`
