### ISSUE TITLE
Column Conditional Create leads to Inifinite cycle of creating/deleting columns

### ISSUE THREAD

**Issue by bgroff-trdrev** [honeycombio/terraform-provider-honeycombio#464]
I've been working to initialize a dataset via HC TF and am running into a problem as I continue to re-plan and re-apply the Terraform that, by using the provided example to conditionally create missing columns, _because of_ the conditional nature of it, on re-run, the opposite action occurs.

https://github.com/honeycombio/terraform-provider-honeycombio/blob/main/example/columns_conditional_create/main.tf

Example scenario for clarity
(Assume apply_honeycomb = true)
```tf
data "honeycombio_columns" "existing_columns" {
  count = var.apply_honeycomb ? 1 : 0

  dataset = local.target_application_name
}

locals {
  pre_init_columns = toset([
    "library.name",
    "trace.trace_id",
    "k8s.cronjob.name",
    "app.error",
    "app.warning",
    "app.consumer_group",
    "trace.trace_id",
    "duration_ms",
    "name",
    "http.response.status_code"
  ])
  cols_to_create = var.apply_honeycomb ? setsubtract(local.pre_init_columns, flatten(data.honeycombio_columns.existing_columns[*].names)) : toset([])
}

resource "honeycombio_column" "pre_init_column" {
  for_each   = local.cols_to_create
  name       = each.key
  type       = "string"
  dataset    = local.target_application_name
  depends_on = [data.honeycombio_columns.existing_columns]
}

```

1. On my first TF Plan and Apply, it is determined that _all_ of the `local.pre_init_columns` need to be created. And they do create. 

2. 2 days later, I need to update one of my queries somewhere else in the terraform and then need to re-Plan and re-Apply. When I re-plan, `existing_columns` contains all of my `pre_init_columns`, and thus `local.cols_to_create` is empty. My previous/current TF State has saved that it manages all of the `local.pre_init_columns`, but not it's evaluated that the `resource "honeycombio_column" "pre_init_column"` is empty, meaning Terraform declares it needs to delete all of these resources. 
Because of this, my next Apply will fail because my query(s) won't have the columns they need. So I'm forced to re-run the Plan and apply _again_, which will loop back to run scenario 1, re-create my missing columns, and now my plan should apply successfully.

My question here is, how can we avoid this? Should the `honeycombio_column` shift to a similar paradigm as the `honeycomb_dataset` resource, which is "read or create"?

**Comment by jharley** [comment]
Hey, @bgroff-trdrev!

Sorry for the confusion here: this example doesn't work properly and should be removed and replaced with a workaround using [null_resource](https://registry.terraform.io/providers/hashicorp/null/latest/docs/resources/resource).

I'll try to get that sorted in the next few days.

**Comment by jharley** [comment]
Updated example landed. Thanks for raising this, @bgroff-trdrev!

> Should the honeycombio_column shift to a similar paradigm as the honeycomb_dataset resource, which is "read or create"?

The column resource did work like this prior to v0.13.0 of the provider, and it was changed because the behaviour is dangerous (now that columns will be deleted by the provider) and not the way Terraform is intended to work.

The datasource resource shouldn't work like this either and its behaviour will change to not do this before we cut `v1.0` of the provider.
