### ISSUE TITLE
Resource: api key

### ISSUE THREAD

**Issue by kvrhdn** [honeycombio/terraform-provider-honeycombio#5]
A resource to manage API keys.

More information: _no documentation available_
API: _there is no API yet for this_

Possible Terraform config:

```hcl
resource "honeycombio_api_key" "example" {
  name   = "Backend"
  enable = true

  permissions = ["send_events"]
}

# honeycombio_api_key exports the field `key`
```

**Comment by dstrelau** [comment]
Adding the new APIs to support this is on the team's roadmap in the near-ish future.

**Comment by DavidS-ovm** [comment]
I think the API has now been released.

/subscribe

**Comment by jharley** [comment]
@DavidS-ovm it has indeed! I'm just wrapping something else up and then am going to pickup this work.
