### ISSUE TITLE
"Error 400 bad request": unknown column name when creating SLIs referencing derived column names

### ISSUE THREAD

**Issue by jlewi** [honeycombio/terraform-provider-honeycombio#509]
I'm trying to create SLIs that reference a derived column name in their expression like so.

```
resource "honeycombio_derived_column" "sli_with_derived" {
  alias       = "sli.with_derived"
  dataset     = "api"

  expression = <<-EOT
      IF(
        AND(             
            NOT(IN($prediction.status, "processing", "starting")), 
            EQUALS($derived.prediction.is_important, 1),
        ),         
        LT($prediction.timings.queue_time, 60)        
      )
    EOT
}
```

Here `derived.prediction.is_important` is a derived column I created in the UI.  When I run `terraform apply` I get.

```
honeycombio_derived_column.sli_with_derived: Creating...
╷
│ Error: 400 Bad Request: unknown column name: derived.prediction.is_important
│ 
│   with honeycombio_derived_column.is_important,
│   on slos.tf line 66, in resource "honeycombio_derived_column" "sli_with_derived":
│   66: resource "honeycombio_derived_column" "sli_with_derived" {
│ 
```

If I remove the derived column names from the expression than it works. 
I can create SLIs in the UI that reference the derived column name.

Do derived columns need to be referenced a special way?

**Comment by jlewi** [comment]
So I saw this example: https://github.com/honeycombio/terraform-provider-honeycombio/issues/310#issuecomment-2018651029

It looks like that uses a reference to the TF resource for the derived column to be referenced to then access that expression and then nest that expression in the definition of the new derived column that wants to reference the expression of the first one.

**Comment by jharley** [comment]
Hey, @jlewi! Thanks for the question.

If you're making the derived column in the same plan/apply cycle (which sounds to be true?) you will need to use a [depends_on](https://developer.hashicorp.com/terraform/language/meta-arguments/depends_on) meta-argument to explicitly setup the dependency as the Terraform dep. solver can't tell what is a derived column in your block of text from anything else.

Something like this:
```hcl
resource "honeycombio_derived_column" "sli_with_derived" {
  alias       = "sli.with_derived"
  dataset     = "api"

  expression = <<-EOT
      IF(
        AND(             
            NOT(IN($prediction.status, "processing", "starting")), 
            EQUALS($derived.prediction.is_important, 1),
        ),         
        LT($prediction.timings.queue_time, 60)        
      )
    EOT

  depends_on = [honeycombio.derived_column.prediction_timings_queue_time]
}
```

**Comment by jlewi** [comment]
Thanks @jharley. I'm actually not creating the derived columns in Honeycomb. The columns (`queue_time`, `is_important`) already exist in Honeycomb and I'm just trying to create new columns that reference it.

**Comment by jharley** [comment]
Interesting! Does the derived column exist in the `api` dataset? Or is it maybe a environment-wide derived column?

**Comment by jlewi** [comment]
Yes I think it exists in the api dataset and isn't environment. In the UI it shows up under the api not environment settings.
I can also fetch it via the honeycomb API using the URL
https://api.honeycomb.io/1/derived_columns/${DATASET}"

**Comment by jlewi** [comment]
@jharley Are you able to refer to other derived columns by name in the expression for a new TF Config.

**Comment by jharley** [comment]
I apologize: I believe I have misread the above.

A Derived Column cannot reference another Derived Column currently: and that is consistent in both the UI and API. If that is what you are trying to do then inlining is the best choice currently.

**Comment by jharley** [comment]
@jlewi I'm going to close this out. Please open a new issue with any new questions. Apologies again for my initial confusion
