### ISSUE TITLE
Migrate away from query spec and use query_id instead

### ISSUE THREAD

**Issue by kvrhdn** [honeycombio/terraform-provider-honeycombio#55]
With the introduction of [the new queries API](https://docs.honeycomb.io/api/queries/), triggers and boards now link to their queries using a `query_id`. To ease the transition the triggers and boards API will temporarily return both values (the original `query` and the new `query_id`).

We should refactor the Terraform logic so we don't rely on `query` anymore and instead fetch the query specification using `query_id`.

**Comment by jharley** [comment]
Resolved by #98
