### ISSUE TITLE
Rename data source honeycombio_query to honeycombio_query_spec

### ISSUE THREAD

**Issue by kvrhdn** [honeycombio/terraform-provider-honeycombio#65]
With the new honeycombio_query resource, it becomes confusing to have to differentiate between the `honeycombio_query` [data source](https://github.com/kvrhdn/terraform-provider-honeycombio/blob/main/docs/data-sources/query.md) and [the resource](https://github.com/kvrhdn/terraform-provider-honeycombio/blob/main/docs/resources/query.md).
The `honeycombio_query` data source is not actually a query though, it's a query specification as used described [in the docs](https://docs.honeycomb.io/api/query-specification/).

To avoid this confusion we should:
- rename the `honeycombio_query` data source to `honeycombio_query_spec`
- rename attributes that expect a query specification from `query` to `query_spec`

**Comment by sleeping-barber** [comment]
Hej @kvrhdn 
First of all, thanks for creating/providing this provider. We are adopting it currently into our workflow.

Reading this issue, I would vote for being consistent with the naming from `honeycomb` documentation. There is a unambiguous difference in `query` and `query_id` (https://docs.honeycomb.io/api/triggers/#fields-on-a-trigger).

If so, we should leave the attributes for the `honeycombio_query_spec` datasource but after we introduced the `query` resource we should name those attributes `query_id`.

Thoughts?
