### ISSUE TITLE
Title / description of query added to boards?

### ISSUE THREAD

**Issue by bodymindarts** [honeycombio/terraform-provider-honeycombio#84]
Every query I add to a board has `Untitled Query` as a name. If I change it manually in the web-ui but re-run `terraform apply` it reverts back. Is there a way to add a `query_annotation` to a query that gets added to a board?

**Comment by jharley** [comment]
In order to annotate a query the query needs to be persisted as a Query object (not inline in the board definition). #82 is up for review and will make this possible.

**Comment by hsophie-sf** [comment]
We are also facing this issue. When is #82 going to be released?

**Comment by jharley** [comment]
Support for this was just merged with #100
